spring:
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
management:
  security:
    enabled: false
etcd:
  keyPrefixOrder:
    - profile
    - application
    - label
  httpsEnabled: false
  urls:
    - "192.168.1.100:2379"
    - "192.168.1.100:2381"
    - "192.168.1.100:2383"
redis:
  distributedlockEnabled: true
  lockWaitTime: 2
  lockLeaseTime: 5
  urls: 
    - "192.168.1.100:6379"