spring:
  rabbitmq:
    host: 192.168.1.100
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
management:
  security:
    enabled: false
etcd:
  urls:
    - "http://192.168.1.100:2379"
    - "http://192.168.1.100:2381"
    - "http://192.168.1.100:2383"