spring:
  rabbitmq:
    host: example-rabbitmq
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
management:
  security:
    enabled: false
etcd:
  keyPrefixOrder:
    - profile
    - application
    - label
  httpsEnabled: false
  urls:
    - "example-etcd:2379"    
redis:
  distributedlockEnabled: true
  lockWaitTime: 2
  lockLeaseTime: 5
  urls: 
    - "example-redis:6379"